#!/bin/bash -e

usage() {
  echo "Usage: $0 [-b] [-n] <server> <xstart> <ystart> <xdelta> <ydelta> <filename>"
}

border=0
convert=convert
curl='curl -f -s'

while getopts 'bn' opt; do
  case $opt in
    b ) border=1 ;;
    n ) convert="echo $convert"; curl="echo $curl" ;;
    ? ) usage; exit 1;;
  esac
done

shift $(($OPTIND - 1))

[ $# -lt 6 ] && usage && exit 2
[[ ! $2 =~ ^[0-9]+$ ]] && usage && exit 3
[[ ! $3 =~ ^[0-9]+$ ]] && usage && exit 4
[[ ! $4 =~ ^[0-9]+$ ]] && usage && exit 5
[[ ! $5 =~ ^[0-9]+$ ]] && usage && exit 6

server=$1
xstart=$2
ystart=$3
xdelta=$4
ydelta=$5
xend=$(( $xstart + $xdelta ))
yend=$(( $ystart + $ydelta ))
blocks=$(( $xdelta * $ydelta ))
img=$6

mkdir -p blocks
echo -n "retrieving $blocks blocks "
for (( x=$xstart; x<$xend; x++ )); do
  for (( y=$ystart; y<$yend; y++ )); do
    o="blocks/x${x}y${y}.jpg"
    [ ! -f $o ] && ${curl} -o $o "http://${server}/kh/v=699&x=${x}&y=${y}&z=20" && [ $border -gt "0" ] && ${convert} $o -border $border $o
    echo -n .
  done
done
echo

mkdir -p strips
echo -n "stitching $xdelta strips "
for (( x=$xstart; x<$xend; x++ )); do
  ${convert} `seq -s' ' -f"blocks/x${x}y%g.jpg" $ystart $(($yend - 1))` -append "strips/l${x}.jpg"
  echo -n '|'
done
echo

echo -n 'stitching final image: '
${convert} `seq -s' ' -f'strips/l%g.jpg' $xstart $(($xend - 1))` +append $img
echo $img
